import { registry } from './PluginRegistry';

const ExamplePlugin = {
  name: 'Simple SEO Optimizer',
  
  // 1. Adds a tab to the Admin Dashboard
  adminTab: { id: 'seo-optimizer', label: '🔍 SEO Settings' },
  
  // 2. Renders the content when the tab is clicked
  renderAdminPanel: (context) => (
    <div className="admin-section">
      <h3>Search Engine Optimization</h3>
      <p>Manage your meta tags, indexing, and site visibility.</p>
      <div style={{ marginTop: '20px', display: 'flex', flexDirection: 'column', gap: '10px', maxWidth: '400px' }}>
        <label><input type="checkbox" defaultChecked /> Enable Google Indexing</label>
        <label><input type="checkbox" defaultChecked /> Auto-generate XML Sitemap</label>
        <input type="text" placeholder="Global Meta Keywords (comma separated)" className="search-input" style={{ width: '100%', padding: '8px', boxSizing: 'border-box' }}/>
        <button className="btn-save" style={{ marginTop: '10px', padding: '10px', background: '#007bff', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer' }}>Save SEO Settings</button>
      </div>
      <p style={{ marginTop: '20px', fontSize: '12px', color: '#666' }}><em>This UI was injected via the plugin system!</em></p>
    </div>
  ),

  // 3. Adds an entire new standalone page to the app route
  pageRoute: 'seo-sitemap',
  renderPage: (context) => (
    <div className="article-page" style={{textAlign: 'center', marginTop: '50px'}}>
      <h2>XML Sitemap (Simulated)</h2>
      <p>This page simulates an SEO sitemap route generated by a plugin.</p>
      <button className="back-button" onClick={() => context.setCurrentPage('home')}>Return to Home</button>
    </div>
  )
};

// Register the plugin with the core system
registry.register(ExamplePlugin);